### ISSUE TITLE
It's not possible to set the access rights for "download" or "location" using SDR client flags for `sdr deposit`

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sdr-client#296]
If I try to use `--download` as a flag, the client appears to interpret that as a filename

```
sdr deposit 01.txt --url "$SERVICE_URL_QA" --label "rights via API" --admin-policy 'druid:ry750zn2918' --source-id "berger:$(uuidgen)" --type "object" --view "world" --download "world"
/Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:50:in `initialize': No such file or directory @ rb_sysopen - /Users/bergeraj/working_directory/hierarchical-files/sample/--download (Errno::ENOENT)
	from /Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:50:in `open'
	from /Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:50:in `file'
	from /Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:35:in `file'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder_operations/md5.rb:12:in `for'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:36:in `block (2 levels) in build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:35:in `each'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:35:in `block in build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:34:in `each'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:34:in `build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:22:in `build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit.rb:40:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:167:in `block in register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:116:in `rescue_expected_exceptions'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:164:in `register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:90:in `deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/exe/sdr:9:in `<top (required)>'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `load'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `<main>'
```

Same with location:

```
sdr deposit 01.txt --url "$SERVICE_URL_QA" --label "rights via API" --admin-policy 'druid:ry750zn2918' --source-id "berger:$(uuidgen)" --type "object" --view "location-based" --location "spec"
/Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:50:in `initialize': No such file or directory @ rb_sysopen - /Users/bergeraj/working_directory/hierarchical-files/sample/--location (Errno::ENOENT)
	from /Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:50:in `open'
	from /Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:50:in `file'
	from /Users/bergeraj/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/digest.rb:35:in `file'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder_operations/md5.rb:12:in `for'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:36:in `block (2 levels) in build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:35:in `each'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:35:in `block in build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:34:in `each'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:34:in `build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/file_metadata_builder.rb:22:in `build'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit.rb:40:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:167:in `block in register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:116:in `rescue_expected_exceptions'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:164:in `register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:90:in `deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/exe/sdr:9:in `<top (required)>'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `load'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `<main>'
```

If you try to specify "location-based" for "view" and leave the other fields out, there's a validation error after the file upload because the actual location has not been specified:

```
sdr deposit 01.txt --url "$SERVICE_URL_QA" --label "rights via API" --admin-policy 'druid:ry750zn2918' --source-id "berger:$(uuidgen)" --type "object" --view "location-based"
I, [2023-08-16T14:45:40.552103 #80696]  INFO -- : checking to see if files exist
I, [2023-08-16T14:45:40.552401 #80696]  INFO -- : Starting an upload request: {"blob":{"filename":"01.txt","byte_size":2,"checksum":"sCYyTGkEsqnLS4jW1hyB0Q==","content_type":"text/plain"}}
I, [2023-08-16T14:45:40.674541 #80696]  INFO -- : Response from server: {"id":24455,"key":"jd8va7sdnknw2l7s2m5brnab5soz","filename":"01.txt","content_type":"text/plain","metadata":{},"byte_size":2,"checksum":"sCYyTGkEsqnLS4jW1hyB0Q==","created_at":"2023-08-16T21:45:40.676Z","service_name":"local","signed_id":"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2RmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7f47158e8af7e2f840802b8e826d3a4a0c59719f","direct_upload":{"url":"https://sdr-api-qa.stanford.edu/v1/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9JYTJWNVNTSWhhbVE0ZG1FM2MyUnVhMjUzTW13M2N6SnROV0p5Ym1GaU5YTnZlZ1k2QmtWVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWc5MFpYaDBMM0JzWVdsdUJqc0dWRG9UWTI5dWRHVnVkRjlzWlc1bmRHaHBCem9OWTJobFkydHpkVzFKSWgxelExbDVWRWRyUlhOeGJreFROR3BYTVdoNVFqQlJQVDBHT3daVU9oRnpaWEoyYVdObFgyNWhiV1U2Q214dlkyRnMiLCJleHAiOiIyMDIzLTA4LTE2VDIyOjA1OjQwLjY4MFoiLCJwdXIiOiJibG9iX3Rva2VuIn19--a3a7631e0614f41e86da9c9a1619b5506ff68512","headers":{"Content-Type":"text/plain"}}}
I, [2023-08-16T14:45:40.674787 #80696]  INFO -- : Uploading `01.txt' to https://sdr-api-qa.stanford.edu/v1/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9JYTJWNVNTSWhhbVE0ZG1FM2MyUnVhMjUzTW13M2N6SnROV0p5Ym1GaU5YTnZlZ1k2QmtWVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWc5MFpYaDBMM0JzWVdsdUJqc0dWRG9UWTI5dWRHVnVkRjlzWlc1bmRHaHBCem9OWTJobFkydHpkVzFKSWgxelExbDVWRWRyUlhOeGJreFROR3BYTVdoNVFqQlJQVDBHT3daVU9oRnpaWEoyYVdObFgyNWhiV1U2Q214dlkyRnMiLCJleHAiOiIyMDIzLTA4LTE2VDIyOjA1OjQwLjY4MFoiLCJwdXIiOiJibG9iX3Rva2VuIn19--a3a7631e0614f41e86da9c9a1619b5506ff68512
I, [2023-08-16T14:45:40.761775 #80696]  INFO -- : Upload of 01.txt complete
/Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/open_api_validator.rb:23:in `rescue in validate': {"view"=>"location-based", "download"=>"none"} isn't one of in #/components/schemas/Access (Cocina::Models::ValidationError)
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/open_api_validator.rb:8:in `validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/validator.rb:31:in `block in validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/validator.rb:31:in `each'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/validator.rb:31:in `validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validatable.rb:11:in `new'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models.rb:117:in `build_request'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/process.rb:60:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit.rb:66:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:167:in `block in register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:116:in `rescue_expected_exceptions'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:164:in `register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:90:in `deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/exe/sdr:9:in `<top (required)>'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `load'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `<main>'
/Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/openapi_parser-0.15.0/lib/openapi_parser/schema_validator.rb:63:in `validate_data': {"view"=>"location-based", "download"=>"none"} isn't one of in #/components/schemas/Access (OpenAPIParser::NotOneOf)
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/openapi_parser-0.15.0/lib/openapi_parser/schema_validator.rb:45:in `validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/openapi_parser-0.15.0/lib/openapi_parser/schemas/media_type.rb:15:in `validate_parameter'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/openapi_parser-0.15.0/lib/openapi_parser/schemas/request_body.rb:24:in `validate_request_body'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/openapi_parser-0.15.0/lib/openapi_parser/schemas/operation.rb:25:in `validate_request_body'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/openapi_parser-0.15.0/lib/openapi_parser/request_operation.rb:52:in `validate_request_body'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/open_api_validator.rb:21:in `validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/validator.rb:31:in `block in validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/validator.rb:31:in `each'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validators/validator.rb:31:in `validate'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models/validatable.rb:11:in `new'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/cocina-models-0.90.0/lib/cocina/models.rb:117:in `build_request'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit/process.rb:60:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/deposit.rb:66:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:167:in `block in register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:116:in `rescue_expected_exceptions'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:164:in `register_or_deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/lib/sdr_client/cli.rb:90:in `deposit'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-2.5.0/exe/sdr:9:in `<top (required)>'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `load'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `<main>'
```

**Comment by andrewjbtw** [comment]
I realized just after posting that I was running ruby 3.0.0, as you can see in the errors. FWIW, I re-ran the commands under ruby 3.2.0 after updating the gem and got the same result. I think the client implementation pre-dates the "download" and "location" fields being separate. It probably supported the specific values that used to appear on the Argo rights menu.

**Comment by andrewjbtw** [comment]
In terms of impact, I'm the only consumer of the sdr-client on the command-line. I mainly use it to quickly create test data, so being able to set rights correctly would benefit me but it isn't high impact in terms of the SDR user base.

**Comment by andrewjbtw** [comment]
The `help` command suggests this is partially implemented for `sdr update`:

```Usage:
  sdr update DRUID

Options:
  -s,             [--skip-polling], [--no-skip-polling]          # Print out job ID instead of polling for result
  --admin-policy, [--apo=APO]                                    # Druid identifier of the admin policy object
                  [--collection=COLLECTION]                      # Druid identifier of the collection object
                  [--copyright=COPYRIGHT]                        # Copyright statement
                  [--use-and-reproduction=USE_AND_REPRODUCTION]  # Use and reproduction statement
                  [--license=LICENSE]                            # License URI
                  [--view=VIEW]                                  # Access view level for the object
                                                                 # Possible values: world, stanford, location-based, citation-only, dark
                  [--download=DOWNLOAD]                          # Access download level for the object
                                                                 # Possible values: world, stanford, location-based, none
                  [--location=LOCATION]                          # Access location for the object
                                                                 # Possible values: spec, music, ars, art, hoover, m&m
                  [--cdl], [--no-cdl]                            # Controlled digital lending
                  [--cocina-file=COCINA_FILE]                    # Path to a file containing Cocina JSON
                  [--cocina-pipe], [--no-cocina-pipe]            # Indicate Cocina JSON is being piped in
                  [--basepath=BASEPATH]                          # Base path for the files
                                                                 # Default: /Users/bergeraj/working_directory/hierarchical-files/sample
                  [--url=URL]                                    # URL of SDR API endpoint
                                                                 # Default: https://sdr-api-prod.stanford.edu
```
but not for `sdr deposit`
```
Usage:
  sdr deposit OPTIONAL_FILES --admin-policy, --apo=APO --source-id=SOURCE_ID

Options:
  -s,             [--skip-polling], [--no-skip-polling]          # Print out job ID instead of polling for result
  --admin-policy, --apo=APO                                      # Druid identifier of the admin policy object
                  --source-id=SOURCE_ID                          # Source ID for this object
                  [--label=LABEL]                                # Object label
                  [--type=TYPE]                                  # The object type
                                                                 # Possible values: image, book, document, map, manuscript, media, three_dimensional, object, collection, admin_policy
                  [--collection=COLLECTION]                      # Druid identifier of the collection object
                  [--catkey=CATKEY]                              # Symphony catkey for this item
                  [--folio-instance-hrid=FOLIO_INSTANCE_HRID]    # Folio instance HRID for this item
                  [--copyright=COPYRIGHT]                        # Copyright statement
                  [--use-and-reproduction=USE_AND_REPRODUCTION]  # Use and reproduction statement
                  [--viewing-direction=VIEWING_DIRECTION]        # Viewing direction (if a book)
                                                                 # Possible values: left-to-right, right-to-left
                  [--view=VIEW]                                  # Access view level for the object
                                                                 # Possible values: world, stanford, location-based, citation-only, dark
                  [--files-metadata=FILES_METADATA]              # JSON string representing per-file metadata
                  [--grouping-strategy=GROUPING_STRATEGY]        # Strategy for grouping files into filesets
                                                                 # Possible values: default, filename
                  [--basepath=BASEPATH]                          # Base path for the files
                                                                 # Default: /Users/bergeraj/working_directory/hierarchical-files/sample
                  [--url=URL]                                    # URL of SDR API endpoint
                                                                 # Default: https://sdr-api-prod.stanford.edu
```

**Comment by peetucket** [comment]
I may have a small fix that on my laptop, but I'd like your assistance in testing it out...   this is the draft PR which  I think you can pull that branch down and see if it works locally for you: https://github.com/sul-dlss/sdr-client/pull/331
