### ISSUE TITLE
Should be able to deposit without a collection

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-client#76]
```
$ ./exe/sdr --service-url https://sdr-api-stage.stanford.edu deposit --admin-policy druid:cx087xf3798 --source_id justin:test1
I, [2020-02-27T14:28:00.167806 #49916]  INFO -- : checking to see if files exist
I, [2020-02-27T14:28:00.212746 #49916]  INFO -- : Starting upload metadata: {:access=>{}, :type=>"http://cocina.sul.stanford.edu/models/book.jsonld", :administrative=>{:hasAdminPolicy=>"druid:cx087xf3798"}, :identification=>{:sourceId=>"justin:test1"}, :structural=>{}}
Traceback (most recent call last):
	5: from ./exe/sdr:112:in `<main>'
	4: from /Users/jcoyne85/workspace/sul-dlss/sdr-client/lib/sdr_client/cli.rb:9:in `start'
	3: from /Users/jcoyne85/workspace/sul-dlss/sdr-client/lib/sdr_client/deposit.rb:36:in `run'
	2: from /Users/jcoyne85/workspace/sul-dlss/sdr-client/lib/sdr_client/deposit/process.rb:38:in `run'
	1: from /Users/jcoyne85/workspace/sul-dlss/sdr-client/lib/sdr_client/deposit/process.rb:57:in `upload_metadata'
/Users/jcoyne85/workspace/sul-dlss/sdr-client/lib/sdr_client/deposit/process.rb:65:in `unexpected_response': There was an error with your request: {"id":"bad_request","message":"#/components/schemas/DROStructural missing required parameters: isMemberOf"} (RuntimeError)
```

**Comment by jcoyne** [comment]
Fixed by https://github.com/sul-dlss/sdr-api/pull/160#event-3098370476
